---
title: "Pokemon Tournament Analysis"
author: "Jackson Marsh and Mario Rodriguez"
date: "2024-12-11"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
      theme: yeti
      vertical_layout: scroll
---

```{r}
#| echo: false

# Importing Libraries for the flexdashboard
library(tidyverse)
library(plotly)
library(flexdashboard)
library(ggthemes)
library(shinyWidgets)
library(kableExtra)
library(gt)
```

```{r}
#| echo: false

# Reading in the data from the flexdashboard
TypeChart <- read_csv("Data/TypeChart.csv")
national_dex <- read_csv("Data/national_dex_forms.csv")
tournament_results <- read_csv("Data/tournament_results_forms.csv")
```

```{r}
#| echo: false

# Defining custom color palate for Types
type_colors <- c("#9fa19f", "#f08500", "#8eb7f2", "#8b3ecf", "#89531a", "#adaa7e",
               "#92a200", "#6b4172", "#6ea0b9", "#d63624", "#497cf3", "#54a113",
               "#f8d800", "#df497a", "#6ed6ff", "#595ce5", "#494949", "#f0a6d6"
               )
#Giving names to the different colors defined above
names(type_colors) = c("normal", "fighting", "flying", "poison", "ground", "rock",
                       "bug", "ghost", "steel", "fire", "water", "grass",
                       "electric", "psychic", "ice", "dragon", "dark", "fairy")
```

Pokemon Stats
==========================
```{r}
inputPanel(
  selectInput("stat", label = "Key Statistic:",
              choices = c("Health points" = "hp","Attack" = "attack","Defense" = "defense", "Special Attack" = "sp_atk","Special Defense" = "sp_def","Speed" = "speed"))
)
```

Row 
-------------------------

```{r}
renderTable({
  national_dex %>%
  arrange(desc(.data[[input$stat]])) %>%
  slice_head(n = 10) %>%
  select(name, .data[[input$stat]]) %>%
  gt()
})
```

```{r}
renderPlot({
national_dex %>%
  pivot_longer(type1:type2, names_to = NULL, values_to = "type" ) %>%
  filter(!is.na(type)) %>%
  count(type, sort = T) %>%
  ggplot(aes(x = type, y = n, fill = type)) +
  geom_col() + 
  scale_fill_manual(values = type_colors)  + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(title = "Frequency of each type across all pokemon", x = "Type", y = "Frequency")
})
```

```{r}
inputPanel(
  sliderInput("adjust", label = "Adjustment:",
              min = 3, max = 18, value = 1, step = 1)
)
renderTable({
national_dex %>%
  mutate(num_characters = nchar(name)) %>%
  arrange(desc(num_characters)) %>%
  filter(num_characters == input$adjust) %>%
  select(name) %>%
    gt()
})
```


Competitive Analysis
==========================
Column
-----

```{r}
#| echo: false

#Input panel for user to define the Pokemon type shown in graph below
inputPanel(
  selectInput(inputId = "type", 
              label = "Type: ", 
              choices = c("Overall", "Normal", "Fighting", "Flying", "Poison", "Ground", "Rock",
                       "Bug", "Ghost", "Steel", "Fire", "Water", "Grass",
                       "Electric", "Psychic", "Ice", "Dragon", "Dark", "Fairy"),
              selected = "Overall"
  )
)

#Plot
renderPlot({
  #Join tournament_results and national_dex together to get Pokemon stats and types
  tournament_results |> 
  left_join(national_dex, join_by(pokemon, alt_form_name == alt_form)) |>
  #Count how many times a Pokemon is seen (used) in the dataset 
  count(pokemon, name, type1, type2) %>%
  #Optional filter for type, otherwise show results for overall most used Pokemon
  {if(input$type != "Overall") 
    filter(., type1 == str_to_lower(input$type) | type2 == str_to_lower(input$type)) 
    else
      .}|>  
  #Get the top 25 most used Pokemon of the selected type
  slice_max(n, n = 25) |> 
  #Make name a factor and reorder it by how many times the Pokemon appears
  mutate(name = fct_reorder(name, n)) |> 
  #Create Plot
  ggplot(aes(x = name, y = n), fill = input$type) + 
  geom_col() +
  coord_flip() +
  labs(
    title = str_c("Most Commonly Used ", input$type, " Pokemon"),
    x = "Pokemon",
    y = "Times Present on a Team"
  )
})

```


```{r}
#If only one form shows up, that means that only that form was used in the 
#tournament
renderPlot({
#Read in what Pokemon has an Alt form (regional/gender)
has_alt_forms <-read.csv("./Data/has_alt_forms.csv")

tournament_results |> 
  #Join tournament_results and national_dex together to get Pokemon stats and types
  left_join(national_dex, join_by(pokemon, alt_form_name == alt_form)) |> 
  semi_join(has_alt_forms, join_by(pokemon)) |> 
  #Make Pokemon a factor so it doesn't treat it as a number
  mutate(pokemon = factor(pokemon)) |> 
  #Plot
  ggplot(aes(x = name, fill = name)) +
  geom_bar(position = "dodge", show.legend = FALSE) +
  facet_wrap(~pokemon, scales = "free", ncol = 2) +
  coord_flip() +
  labs(
    title = "How Many Times Was an Alternate Form Used Instead of a Base Form",
    x = "Form Name",
    y = "Appearances"
  )
})
```

Column
---

```{r}
#| echo: false

#Input panel for user to define the stat shown in graph below
inputPanel(
  selectInput("stat", label = "Key Statistic:",
              choices = c("Health points" = "hp","Attack" = "attack","Defense" = "defense", "Special Attack" = "sp_atk","Special Defense" = "sp_def","Speed" = "speed"))
)
#Plot
renderPlotly({ 
  #Take the stat inputted by user and translate it from how it is stored in dataset
  #to how it was shown to the user. (Used later on)
  stat_labels <- c(
    hp = "Health Points",
    attack = "Attack",
    defense = "Defense",
    sp_atk = "Special Attack",
    sp_def = "Special Defense",
    speed = "Speed"
  )
  stat_name <- stat_labels[[input$stat]]
  
  #Create data set used for graphing
  #Join tournament_results and national_dex together to get Pokemon stats and types
  stat_df <- tournament_results |> 
    left_join(national_dex, join_by(pokemon, alt_form_name == alt_form)) |> 
    #Get the sum of the selected stat for each team, while keeping the placement info
    group_by(player, placement) |> 
    summarise(total_stat = sum(.data[[input$stat]])) 
  
  #Create plot as a ggplot
  stat_graph <- stat_df|> 
    ggplot(aes(x = player, y = total_stat)) + 
    geom_col() + 
    #Line represents the avg of that stat among all Pokemon, then multiplied by
    #6 to represent the expected sum of that stat for a full team of 6
    geom_hline(yintercept = mean(national_dex[[input$stat]]) * 6, color = "red") + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    labs(
      title = str_c("Sum of the ", stat_name, " Stats of Pokemon on a Team"),
      subtitle = str_c("Red Line Represents Avg ", 
                       stat_name, 
                       " Stat Across All Pokemon Times 6"
                 ),
      x = "Player",
      y = str_c("Total ", stat_name, " Stat for the Team")
    )
  
  #Take ggplot and make it into a plotly plot
  ggplotly(stat_graph) |> 
    #Modify plotly plot so hover text also shows placement information
    style(
      hovertext = paste("Player: ", stat_df$player, "\n",
                           "Total ", stat_name, ": ", stat_df$total_stat, "\n",
                           "Placement: ", stat_df$placement)
    )
})
```


Type Analysis 
======================

```{r}
Typechart2 <- TypeChart %>%
  group_by(...1) %>% 
  mutate(sum_of_attacks = Normal + Fire + Water + Electric + Grass + Ice + Fighting +                                Poison + Ground + Flying + Psychic + Bug + 
                          Rock + Ghost + Dragon + Dark + Steel + Fairy) %>%
  ungroup() %>%
  select(...1, sum_of_attacks) %>%
  mutate(...1 = tolower(...1)) %>%
  rename("type" = "...1") 

renderPlot({
tournament_results |> 
  left_join(national_dex, join_by(pokemon, alt_form_name == alt_form)) |> 
  pivot_longer(type1:type2, names_to = NULL, values_to = "type" ) |> 
  filter(!is.na(type)) |> 
  mutate(type = fct_infreq(type)) %>% 
  count(type) %>%
  right_join(Typechart2) %>%
   ggplot(aes(x = n, y = sum_of_attacks)) +
  geom_point(aes(color = type)) +
  geom_smooth(method = lm, se = F) + 
  scale_color_manual(values = type_colors)
})
```


