---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library(tidyverse)
```

```{r}
#import dataset

tournament_results <- read_csv("./Data/tournament_results_forms.csv")

national_dex <- read.csv("./Data/national_dex_forms.csv")
```

```{r}
tournament_results |> 
  left_join(national_dex, join_by(pokemon, alt_form_name == alt_form))
```

#Define Colors
```{r}
type_colors <- c("#9fa19f", "#f08500", "#8eb7f2", "#8b3ecf", "#89531a", "#adaa7e",
               "#92a200", "#6b4172", "#6ea0b9", "#d63624", "#497cf3", "#54a113",
               "#f8d800", "#df497a", "#6ed6ff", "#595ce5", "#494949", "#f0a6d6"
               )
names(type_colors) = c("normal", "fighting", "flying", "poison", "ground", "rock",
                       "bug", "ghost", "steel", "fire", "water", "grass",
                       "electric", "psychic", "ice", "dragon", "dark", "fairy")
```

#Team Type Composition for Top 10 teams
```{r}
tournament_results |> 
  left_join(national_dex, join_by(pokemon, alt_form_name == alt_form)) |> 
  pivot_longer(type1:type2, names_to = NULL, values_to = "type" ) |> 
  filter(!is.na(type), placement <= 10) |> 
  mutate(type = fct_infreq(type)) |> 
  ggplot(aes(x = player, fill = type)) + 
  geom_bar(color = "white", linewidth = 1) + 
  scale_fill_manual(values = type_colors)+
  coord_flip()
```

#Most Used Pokemon
```{r}
tournament_results |> 
  left_join(national_dex, join_by(pokemon, alt_form_name == alt_form)) |>
  count(pokemon, name, type1, type2) |> 
  slice_max(n, n = 25) |> 
  mutate(name = fct_reorder(name, n)) |> 
  ggplot(aes(x = name, y = n)) + 
  geom_col() +
  coord_flip()
```

#Most Used pokemon of specific type
```{r}
tournament_results |> 
  left_join(national_dex, join_by(pokemon, alt_form_name == alt_form)) |>
  count(pokemon, name, type1, type2) |> 
  filter(type1 == "fairy" | type2 == "fairy") |> 
  slice_max(n, n = 25) |> 
  mutate(name = fct_reorder(name, n)) |> 
  ggplot(aes(x = name, y = n)) + 
  geom_col() +
  coord_flip()
```

```{r}
tournament_results |> 
  left_join(national_dex, join_by(pokemon, alt_form_name == alt_form)) %>% 
  group_by(player) %>%
  mutate(sum = sum(.data[["hp"]])) %>%
  slice_head() %>%
  ggplot(aes(x = player, y = sum)) + 
  geom_col() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
stat_df <- tournament_results |> 
  left_join(national_dex, join_by(pokemon, alt_form_name == alt_form)) |> 
  group_by(player, placement) |> 
  summarise(total_stat = sum(hp)) 

stat_graph <- stat_df|> 
  ggplot(aes(x = player, y = total_stat)) + 
  geom_col() + 
  geom_hline(yintercept = mean(national_dex$hp) * 6, color = "red") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(
    title = str_c("Sum of the ", "hp", " Stats of Pokemon on a Team"),
    subtitle = str_c("Red Line Represents Avg ", 
                     "hp", 
                     " Stat Across All Pokemon Times 6"
               ),
    x = "Player",
    y = str_c("Total ", "hp", " Stat for the Team")
  )

ggplotly(stat_graph) |> 
  style(
    hovertext = paste("Player: ", stat_df$player, "\n",
                         "Total HP: ", stat_df$total_stat, "\n",
                         "Placement: ", stat_df$placement)
  )
  
```

```{r}
has_alt_forms <-read.csv("./Data/has_alt_forms.csv")

tournament_results |> 
  left_join(national_dex, join_by(pokemon, alt_form_name == alt_form)) |> 
  semi_join(has_alt_forms, join_by(pokemon)) |> 
  mutate(pokemon = factor(pokemon)) |> 
  ggplot(aes(x = name, fill = name)) +
  geom_bar(position = "dodge") +
  facet_wrap(~pokemon, scales = "free", ncol = 2) +
  coord_flip()
```

