---
title: "Into Analysis"
output: html_document
date: "2024-12-10"
---

```{r}
library(tidyverse)
```

```{r}
custompal <- c("seagreen", "gray21", "paleturquoise3", "yellow1", "violetred3", "tomato4", "firebrick2", "lightcyan3", "purple4", "lightgreen", "burlywood3", "cadetblue1", "lightpink2", "mediumpurple2", "mediumvioletred", "saddlebrown", "turquoise3", "blue")
```

```{r}
TypeChart <- read_csv("~/TypeChart.csv")
national_dex <- read_csv("Data/national_dex.csv")
tournament_results <- read_csv("Data/tournament_results.csv")
```

```{r}
tournament_results <- tournament_results %>%
  mutate(pokemon = str_extract(pokemon, "\\d\\d(\\d)?(\\d)?"), 
         pokemon = parse_number(pokemon))
```

```{r}
tournament_results$pokemon <- as.character(tournament_results$pokemon)
national_dex$pokemon <- as.character(national_dex$pokemon)
```

```{r}
TypeChart <- TypeChart %>%
rename("Attack" = "...1")
```


```{r}
fulldata <- tournament_results %>%
  left_join(national_dex)
```

```{r}
fulldata %>%
  group_by(player) %>%
  mutate(sum = sum(speed)) %>%
  slice_head() %>%
  select(player, sum) %>%
  ggplot(aes(x = player, y = sum)) + 
  geom_col() + 
  geom_hline(yintercept = mean(national_dex$speed) * 6, color = "red") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  
```
```{r}
mean(national_dex$hp) * 6
```

```{r}
type1 <- fulldata %>%
  group_by(player) %>%
  count(type1) %>%
  ungroup() %>%
  count(type1, sort = T) %>%
  rename("type" = "type1")
```

```{r}
type2 <- fulldata %>%
  group_by(player) %>%
  count(type2) %>%
  ungroup() %>%
  count(type2, sort = T) %>%
  rename("type" = "type2")
```

```{r}
types <- type1 %>%
  full_join(type2) %>%
  group_by(type) %>%
  mutate(sum = sum(n)) %>%
  slice_head() %>%
  select(-n) %>%
  ungroup()
  
types <- na.omit(types)

types <- arrange(types, desc(sum)) 

types %>%
  ggplot(aes(x = type, y = sum, fill = type)) +
  geom_col() + 
  scale_fill_manual(values = custompal) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
fulldata %>%
  count(name, sort = T) %>%
  left_join(national_dex) %>%
  select(name, n, type1, type2)
```

```{r}
TypeChart %>%
  group_by(TypeChart$Attack) %>% 
  mutate(sum_of_attacks = Normal + Fire + Water + Electric + Grass + Ice + Fighting + Poison + Ground + Flying + Psychic + Bug + Rock + Ghost + Dragon + Dark + Steel + Fairy)
```
```{r}
TypeChart %>%
  group_by(Attack) %>%
  filter(Normal == 0)
```
```{r}
TypeChart %>%
  group_by(TypeChart$Attack) %>% 
  mutate(sum_of_attacks = Normal + Fire + Water + Electric + Grass + Ice + Fighting +                                Poison + Ground + Flying + Psychic + Bug + 
                          Rock + Ghost + Dragon + Dark + Steel + Fairy) %>%
  ungroup() %>%
  select(Attack, sum_of_attacks) %>%
  mutate(Attack = tolower(Attack)) %>%
  rename("type" = "Attack") %>%
  left_join(types) %>%
  mutate(sum = replace_na(sum, 9)) %>%
  ggplot(aes(x = sum, y = sum_of_attacks)) +
  geom_point() +
  geom_smooth(method = lm, se = F)
```

```{r}

```

